config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do

  devise_for :users, path: '',
    path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
    controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end


  get '/thank_you' => "static#thank_you"


  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip

  # Channels
  constraints subdomain: 'asas' do
    namespace :channels, path: '' do
      namespace :adm do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :statistics, only: [ :index ]
        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
          end
        end
      end
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
        end
      end
      resources :channels_subscribers, only: [:index, :create, :destroy]
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/guidelines',            to: 'static#guidelines',          as: :guidelines
  get "/guidelines_tips",       to: "static#guidelines_tips",     as: :guidelines_tips
  get "/guidelines_backers",    to: "static#guidelines_backers",  as: :guidelines_backers
  get "/guidelines_start",      to: "static#guidelines_start",    as: :guidelines_start
  get "/about",                 to: "static#about",               as: :about


  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        get 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'video'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    collection do
      get :uservoice_gadget
    end
    resources :backers, controller: 'users/backers', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug
end

app/controllers/adm/backers_controller.rb
class Adm::BackersController < Adm::BaseController
  menu I18n.t("adm.backers.index.menu") => Rails.application.routes.url_helpers.adm_backers_path
  has_scope :by_user_id, :by_key, :user_name_contains, :project_name_contains, :confirmed, :credits, :with_state, :by_value
  has_scope :between_values, using: [ :start_at, :ends_at ], allow_blank: true
  before_filter :set_title

  def self.backer_actions
    %w[confirm pendent refund hide cancel push_to_trash].each do |action|
      define_method action do
        resource.send(action)
        flash[:notice] = I18n.t("adm.backers.messages.successful.#{action}")
        redirect_to adm_backers_path(params[:local_params])
      end
    end
  end
  backer_actions

  def change_reward
    resource.change_reward! params[:reward_id]
    flash[:notice] = I18n.t('adm.backers.messages.successful.change_reward')
    redirect_to adm_backers_path(params[:local_params])
  end

  protected
  def set_title
    @title = t("adm.backers.index.title")
  end

  def collection
    @backers = apply_scopes(end_of_association_chain).without_state('deleted').order("backers.created_at DESC").page(params[:page])
  end
end

app/controllers/adm/base_controller.rb
class Adm::BaseController < ApplicationController
  inherit_resources
  before_filter do
    authorize! :manage, resource_class  
  end

  @@menu_items = {}
  cattr_accessor :menu_items

  def self.menu menu=nil
    if menu
      self.menu_items.merge! menu
    else
      self.menu_items
    end
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.json { respond_with_bip(resource) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(resource) }
      end
    end
  end

  def current_ability
    controller_name_segments = params[:controller].split('/')
    controller_name_segments.pop
    controller_namespace = controller_name_segments.join('/').camelize
    @current_ability ||= Ability.new(current_user, { namespace: controller_namespace })
  end


end

app/controllers/adm/financials_controller.rb
class Adm::FinancialsController < Adm::BaseController
  require 'csv'
  inherit_resources
  defaults  resource_class: Project, collection_name: 'projects', instance_name: 'project'
  menu I18n.t("adm.financials.index.menu") => Rails.application.routes.url_helpers.adm_financials_path
  has_scope :by_permalink, :name_contains, :user_name_contains, :financial, :with_state, :by_progress
  has_scope :between_expires_at, using: [ :start_at, :ends_at ], allow_blank: true

  actions :index

  def projects
    @search = apply_scopes(Project).includes(:user).order("CASE state WHEN 'successful' THEN 1 WHEN 'waiting_funds' THEN 2 ELSE 3 END, (projects.expires_at)::date DESc")
  end

  def collection
    @projects = projects.page(params[:page])
  end

  def index
    respond_to do |format|
      format.html {collection}
      format.csv do
        csv_string = CSV.generate do |csv|
          # header row
          csv << ["name", "moip", "goal", "reached", "moip_tax", "catarse_fee", "repass_value","expires_at", "backer_report", "state"]
          # data rows
          projects.each do |project|
            catarse_fee = ::Configuration[:catarse_fee].to_f * project.pledged
            csv << [project.name,
                    project.user.moip_login,
                    project.display_goal,
                    project.display_pledged,
                    view_context.number_to_currency(project.total_payment_service_fee, precision: 2),
                    view_context.number_to_currency(catarse_fee, precision: 2),
                    view_context.number_to_currency(project.pledged*0.87, precision: 2),
                    project.display_expires_at,
                    adm_reports_backer_reports_url(project_id: project.id, format: :csv),
                    project.state
            ]
          end
        end
        send_data csv_string,
                  type: 'text/csv; charset=iso-8859-1; header=present',
                  disposition: "attachment; filename=financials.csv"
      end
    end
  end

end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :with_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table, default: 'created_at'

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to adm_projects_path
  end

  def collection
    @projects = apply_scopes(end_of_association_chain).without_state('deleted').page(params[:page])
  end
end

app/controllers/adm/reports/backer_reports_controller.rb
class Adm::Reports::BackerReportsController < Adm::Reports::BaseController
  def end_of_association_chain
    super.where(project_id: params[:project_id])
  end
end

app/controllers/adm/reports/base_controller.rb
class Adm::Reports::BaseController < Adm::BaseController
  inherit_resources
  responders :csv
  respond_to :csv
  actions :index
end

app/controllers/adm/statistics_controller.rb
class Adm::StatisticsController < Adm::BaseController
  inherit_resources
  defaults  resource_class: Statistics
  menu I18n.t("adm.statistics.index.menu") => Rails.application.routes.url_helpers.adm_statistics_path
  actions :index
end

app/controllers/adm/users_controller.rb
class Adm::UsersController < Adm::BaseController
  inherit_resources
  menu I18n.t("adm.users.index.menu") => Rails.application.routes.url_helpers.adm_users_path
  before_filter :set_title
  before_filter :set_totals

  has_scope :by_id, :by_name, :by_email, :by_payer_email, :by_key, :has_credits, :has_credits_difference, only: :index

  protected
  def set_totals
    totals = end_of_association_chain.backer_totals
    @total_users = totals[:users].to_i
    @total_backs = totals[:backs]
    @total_backed = totals[:backed]
    @total_credits = totals[:credits]
  end

  def set_title
    @title = t("adm.users.index.title")
  end

  def collection
    @users ||= apply_scopes(end_of_association_chain).order_by(params[:order_by] || 'coalesce(user_totals.sum, 0) DESC').includes(:user_total).page(params[:page])
  end
end

app/controllers/channels/adm/projects_controller.rb
class Channels::Adm::ProjectsController < Adm::BaseController
  menu I18n.t('channels.adm.menu') => Rails.application.routes.url_helpers.adm_projects_path

  
  has_scope :by_id, :pg_search, :user_name_contains, :order_table, :with_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table do |controller, scope, value|
  value.present? ? scope.order_table(value) : scope.order('created_at DESC')
  end



  before_filter do
    @channel        =  Channel.find_by_permalink!(request.subdomain.to_s)
    @total_projects =  @channel.projects.size 
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project    = @channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
    def begin_of_association_chain
      @channel
    end

    def collection
      @projects = apply_scopes(@channel.projects.page(params[:page]))
    end
  

end

app/controllers/channels/adm/reports/subscriber_reports_controller.rb
class Channels::Adm::Reports::SubscriberReportsController < Adm::Reports::BaseController

  private
  def begin_of_association_chain
    Channel.find_by_permalink!(request.subdomain.to_s)
  end
end

app/controllers/channels/adm/statistics_controller.rb
class Channels::Adm::StatisticsController < Adm::BaseController
  menu I18n.t('channels.adm.statistics_menu') => Rails.application.routes.url_helpers.adm_statistics_path

  actions :index

  before_filter do
    @channel = Channel.find_by_permalink!(request.subdomain.to_s)
  end

  def index
    @total_subscribers = @channel.subscribers.count
  end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:create, :update_info]
  skip_before_filter :verify_authenticity_token, only: [:moip]
  has_scope :available_to_count, :waiting_confirmation, type: :boolean
  has_scope :page, default: 1
  load_and_authorize_resource except: [:index]
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def index
    render collection
  end

  def show
    @title = t('projects.backers.show.title')
    session[:thank_you_backer_id] = nil
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {host: ::Configuration[:secure_review_host], protocol: 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', name: @project.name)
    @backer = @project.backers.new(user: current_user)
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)

    # Select
    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @backer.reward = @selected_reward
      @backer.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.user = current_user
    @backer.reward_id = nil if params[:backer][:reward_id].to_i == 0
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      success.html do
        resource.update_current_billing_info
        flash[:notice] = nil
        session[:thank_you_backer_id] = @backer.id
        return render :create
      end
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed?
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end

  protected
  def collection
    @backers ||= apply_scopes(end_of_association_chain).available_to_display.order("confirmed_at DESC").per(10)
  end
end

app/controllers/users/backers_controller.rb
class Users::BackersController < ApplicationController
  inherit_resources
  defaults resource_class: Backer, collection_name: 'backs', instance_name: 'back'
  belongs_to :user
  actions :index

  def index
    render layout: false
  end

  def request_refund
    authorize! :request_refund, resource
    if resource.value > resource.user.user_total.credits
      flash[:failure] = I18n.t('credits.index.insufficient_credits')
    elsif can?(:request_refund, resource) && resource.can_request_refund?
      resource.request_refund!
      flash[:notice] = I18n.t('credits.index.refunded')
    end

    redirect_to user_path(parent, anchor: 'credits')
  end

  protected
  def collection
    @backs = end_of_association_chain.available_to_display.order("created_at DESC, confirmed_at DESC")
    @backs = @backs.not_anonymous.confirmed unless can? :manage, @user
    @backs = @backs.includes(:user, :reward, project: [:user, :category, :project_total]).page(params[:page]).per(10)
  end
end

app/views/adm/backers/index.html.slim
#page_content
  .container
    .title
      h1= t('.title')
      h2
        strong= "#{@total_backers} "
        = t('.total_backers')
        | ·
        strong= "#{@total_backs} "
        = t('.total_backs')
        | ·
        strong= "#{number_to_currency @total_backed, unit: 'R$', precision: 0, delimiter: '.'} "
        = t('.total_backed')
        | ·
        strong= "#{@total_users} "
        = t('.total_users')

    .filters
      .bootstrap-form
        = form_tag adm_backers_path, method: :get, class: 'form-horizontal' do |f|
          fieldset
            .input
              = label_tag :by_user_id, t('.user_id')
              = text_field_tag :by_user_id, params[:by_user_id], class: 'input-small'
            .input
              = label_tag :between_values, t('.between_values')
              = text_field_tag 'between_values[start_at]', (params[:between_values][:start_at] if params[:between_values].present?), class: 'input-small'
              | &nbsp;
              | &nbsp;
              = text_field_tag 'between_values[ends_at]', (params[:between_values][:ends_at] if params[:between_values].present?), class: 'input-small'
            .input
              = label_tag :with_state, t('.with_state')
              = select_tag :with_state, options_for_select(Backer.state_names, params[:with_state]), include_blank: true
            .input
              = label_tag :by_key, t('.key')
              = text_field_tag :by_key, params[:by_key]
            .input
              = label_tag :project_name_contains, t('.project')
              = text_field_tag :project_name_contains, params[:project_name_contains]
            .input
              = label_tag :user_name_contains, t('.user')
              = text_field_tag :user_name_contains, params[:user_name_contains]
            .bootstrap-twitter
              .input.submit
                = submit_tag t('.submit'), class: 'btn btn-success'
          fieldset
            .input.check
              = check_box_tag :credits, :on, params[:credits]
              = label_tag :credits, t('.credits')
            .input.total_results
              #total_results
                = pluralize_without_number collection.count, t('found_singular'), t('found_plural')
                strong= collection.count
                = pluralize_without_number(collection.count, t('backer_singular'), t('backer_plural')).downcase
      .clearfix
      = paginate @backers
      - if @backers.empty?
        = t('.no_backers')
      - else
        .bootstrap-twitter
          table.table.table-striped
            thead
              tr
                th= t('.info')
                th= t('.project')
                th= t('.user')
                th= t('.value')
                th= t('.reward')
                th= t('.key')
                th= t('.anonymous')
                th= t('.credits')
                th= t('.state')
                th
            tbody
              - @backers.includes(:project, :user, :reward).each do |backer|
                tr id=backer.id class=cycle("even", "odd")
                  td
                    .bootstrap-twitter
                      div id="backerInfo#{backer.id}" class="hide modal"
                        .modal-header
                          h3= t('.backer_info', key: backer.key)
                        .modal-body style='text-align: left'
                          p
                            strong= t('.payment_method')
                            | &nbsp;
                            = backer.payment_method
                          p
                            strong= t('.payment_fee')
                            | &nbsp;
                            = number_to_currency backer.payment_service_fee, unit: 'R$', precision: 2, delimiter: '.'
                          p
                            strong= t('.payment_id')
                            | &nbsp;
                            = backer.payment_id
                          p
                            strong= t('.payer_email')
                            | &nbsp;
                            = backer.payer_email
                          p
                            strong= t('.user_email')
                            | &nbsp;
                            = backer.user.email
                          p
                            strong= t('.payment_choice')
                            | &nbsp;
                            = backer.payment_choice
                          p
                            strong= t('.created_at')
                            | &nbsp;
                            = l(backer.created_at)

                        .modal-footer
                          button type='button' data-dismiss="modal" class="btn" OK
                    = link_to "#backerInfo#{backer.id}", class: 'btn btn-mini', data: {toggle:'modal'} do
                      i.icon-info-sign
                  td title=backer.project.name
                    = link_to project_by_slug_path(permalink: backer.project.permalink) do
                      = image_tag backer.project.display_image, class: 'project_img'
                  td title=backer.user.display_name
                    = link_to user_path(backer.user) do
                      = image_tag backer.user.display_image, class: 'user_img'
                    .user_id= best_in_place [:adm, backer], :user_id, method: :put, type: :input
                  td= best_in_place [:adm, backer], :value, method: :put, type: :input
                  td title=("#{backer.reward.display_minimum} - #{backer.reward.description}" if backer.reward)
                    - if backer.reward
                      = backer.reward.display_minimum
                    - else
                      | -
                    .btn-group
                      = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'btn btn-mini dropdown-toggle' do
                        span.caret
                      ul.dropdown-menu
                        li title=("#{t('.no_reward')}" ) = link_to t('.no_reward'), change_reward_adm_backer_path(backer, reward_id: nil), method: :put
                        - backer.available_rewards.each do |reward|
                          li title=("#{reward.display_minimum} - #{reward.description}" ) = link_to reward.minimum_value, change_reward_adm_backer_path(backer, reward_id: reward.id, local_params: params), method: :put

                  td.key= backer.key
                  td.checkbox= best_in_place [:adm, backer], :anonymous, method: :put, type: :checkbox, collection: [t('no'), t('yes')]
                  td= (backer.credits ? t('yes') : t('no'))
                  td= backer.state
                  td.bootstrap-twitter
                    .btn-group
                      = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'btn btn-mini dropdown-toggle' do
                        span.caret
                      ul.dropdown-menu
                        - if backer.confirmed?
                          li= link_to t('adm.backers.index.unconfirm_backer'), pendent_adm_backer_path(backer, local_params: params), method: :put
                        - else
                          li= link_to t('adm.backers.index.confirm_backer'), confirm_adm_backer_path(backer, local_params: params), method: :put
                        - if backer.requested_refund? or backer.confirmed?
                          li= link_to t('adm.backers.index.refund_backer'), refund_adm_backer_path(backer, local_params: params), method: :put
                        li= link_to t('adm.backers.index.refund_and_hide'), hide_adm_backer_path(backer, local_params: params), method: :put
                        li= link_to t('adm.backers.index.cancel'), cancel_adm_backer_path(backer, local_params: params), method: :put
                        li= link_to t('adm.backers.index.push_to_trash'), push_to_trash_adm_backer_path(backer, local_params: params), method: :put
      = paginate @backers
  .clearfix