config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do

  devise_for :users, path: '',
    path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
    controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end


  get '/thank_you' => "static#thank_you"


  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip

  # Channels
  constraints subdomain: 'asas' do
    namespace :channels, path: '' do
      namespace :adm do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :statistics, only: [ :index ]
        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
          end
        end
      end
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
        end
      end
      resources :channels_subscribers, only: [:index, :create, :destroy]
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/guidelines',            to: 'static#guidelines',          as: :guidelines
  get "/guidelines_tips",       to: "static#guidelines_tips",     as: :guidelines_tips
  get "/guidelines_backers",    to: "static#guidelines_backers",  as: :guidelines_backers
  get "/guidelines_start",      to: "static#guidelines_start",    as: :guidelines_start
  get "/about",                 to: "static#about",               as: :about


  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        get 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'video'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    collection do
      get :uservoice_gadget
    end
    resources :backers, controller: 'users/backers', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug
end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :with_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table, default: 'created_at'

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to adm_projects_path
  end

  def collection
    @projects = apply_scopes(end_of_association_chain).without_state('deleted').page(params[:page])
  end
end

app/controllers/channels/adm/projects_controller.rb
class Channels::Adm::ProjectsController < Adm::BaseController
  menu I18n.t('channels.adm.menu') => Rails.application.routes.url_helpers.adm_projects_path

  
  has_scope :by_id, :pg_search, :user_name_contains, :order_table, :with_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table do |controller, scope, value|
  value.present? ? scope.order_table(value) : scope.order('created_at DESC')
  end



  before_filter do
    @channel        =  Channel.find_by_permalink!(request.subdomain.to_s)
    @total_projects =  @channel.projects.size 
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project    = @channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
    def begin_of_association_chain
      @channel
    end

    def collection
      @projects = apply_scopes(@channel.projects.page(params[:page]))
    end
  

end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id


  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [@channel] }
  after_filter only: [:create] { notify_trustees }

  prepend_before_filter{ params[:profile_id] = request.subdomain }




  # After a project submission through a channel, notify all channel's trustees
  protected
    def notify_trustees

    end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:create, :update_info]
  skip_before_filter :verify_authenticity_token, only: [:moip]
  has_scope :available_to_count, :waiting_confirmation, type: :boolean
  has_scope :page, default: 1
  load_and_authorize_resource except: [:index]
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def index
    render collection
  end

  def show
    @title = t('projects.backers.show.title')
    session[:thank_you_backer_id] = nil
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {host: ::Configuration[:secure_review_host], protocol: 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', name: @project.name)
    @backer = @project.backers.new(user: current_user)
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)

    # Select
    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @backer.reward = @selected_reward
      @backer.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.user = current_user
    @backer.reward_id = nil if params[:backer][:reward_id].to_i == 0
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      success.html do
        resource.update_current_billing_info
        flash[:notice] = nil
        session[:thank_you_backer_id] = @backer.id
        return render :create
      end
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed?
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end

  protected
  def collection
    @backers ||= apply_scopes(end_of_association_chain).available_to_display.order("confirmed_at DESC").per(10)
  end
end

app/controllers/projects/updates_controller.rb
class Projects::UpdatesController < ApplicationController
  inherit_resources
  load_and_authorize_resource

  actions :index, :create, :destroy
  belongs_to :project

  def show
    render resource
  end

  def index
    render end_of_association_chain.page(params[:page]).per(3)
  end

  def create
    @update = parent.updates.create(params[:update].merge!(user: current_user))
    render @update
  end

  def destroy
    destroy!{|format| return index }
  end

  def collection
    @updates ||= end_of_association_chain.visible_to(current_user)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  load_and_authorize_resource only: [ :new, :create, :update, :destroy ]
  inherit_resources
  has_scope :pg_search, :by_category_id, :near_of
  has_scope :recent, :expiring, :successful, :recommended, :not_expired, type: :boolean

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  def index
    index! do |format|
      format.html do
        if request.xhr?
          @projects = apply_scopes(Project).visible.order_for_search.includes(:project_total, :user, :category).page(params[:page]).per(6)
          return render partial: 'project', collection: @projects, layout: false
        else
          @title = t("site.title")
          if current_user && current_user.recommended_projects.present?
            @recommends = current_user.recommended_projects.limit(3)
          else
            @recommends = ProjectsForHome.recommends
          end

          @channel_projects = Project.from_channels.order_for_search.limit(3)
          @projects_near = Project.with_state('online').near_of(current_user.address_state).order("random()").limit(3) if current_user
          @expiring = ProjectsForHome.expiring
          @recent   = ProjectsForHome.recents
        end
      end
    end
  end

  def new
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end

  def create
    @project = current_user.projects.new(params[:project])

    create!(notice: t('projects.create.success')) do |success, failure|
      success.html{ return redirect_to project_by_slug_path(@project.permalink) }
    end
  end

  def update
    update! do |success, failure|
      success.html{ return redirect_to project_by_slug_path(@project.permalink, anchor: 'edit') }
      failure.html{ return redirect_to project_by_slug_path(@project.permalink, anchor: 'edit') }
    end
  end

  def show
    @title = resource.name
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
    @updates_count = resource.updates.count
    @update = resource.updates.where(id: params[:update_id]).first if params[:update_id].present?
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  end

  %w(embed video_embed).each do |method_name|
    define_method method_name do
      @title = resource.name
      render layout: 'embed'
    end
  end

  def embed_panel
    @title = resource.name
    render layout: false
  end

  protected

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < ApplicationController
  inherit_resources
  actions :index
  belongs_to :user

  def index
    render layout: false
  end

  def collection
    @projects ||= end_of_association_chain.page(params[:page]).per(10)
  end
end

app/views/projects/_project.html.slim
.project-box[itemscope itemtype="http://schema.org/CreativeWork" class=(custom_class if defined?(custom_class))]
  meta[itemprop="dateCreated" content=project.created_at.to_date]
  - if project.expired?
    .status-flag
      = link_to project_by_slug_path(permalink: project.permalink), target: ( defined?(embed_link) ? '__blank' : '' ) do
        - if project.successful?
          = image_tag "successful.#{I18n.locale}.png"
        - elsif project.failed?
          = image_tag "not_successful.#{I18n.locale}.png"
        - else
          = image_tag "waiting_confirmation.#{I18n.locale}.png"
  .image = link_to image_tag(project.display_image, size: '220x140'), project_by_slug_path(project.permalink), title: project.name
  .padding
    h4.title    = link_to truncate(project.name, length: 50, separator: ''), project_by_slug_path(project.permalink), title: project.name
    p.headline  = link_to truncate(project.headline, length: 140), project_by_slug_path(project.permalink), title: project.headline
  .status
    .padding
      p.progress-percent = t('channels.projects.progress_html', percent: project.progress)
      .progress-bar = project.progress_bar
      = link_to t('channels.projects.time_remaining_html', count: project.time_to_go[:time], unit: project.time_to_go[:unit]), project_by_slug_path(project.permalink), title: project.name, class: 'time-remaining'
      = link_to t('channels.projects.pledged_html', value: number_to_currency(project.pledged, precision: 0)), project_by_slug_path(project.permalink), title: project.name, class: 'money-raised'

app/views/projects/_project_about.html.slim
.media
  .video
    iframe src="#{@project.display_video_embed_url}" width="640" height="430" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen
  .social
    #project_share
      #facebook_share= render_facebook_like href: project_by_slug_url(@project.permalink, locale: I18n.locale)
      ul
        li.embed
          = link_to '#embed', id: 'embed_link' do
            = image_tag "catarse/embed_icon19x9.png", title: t('projects.show.share.embed_title')
            = t('projects.show.share.embed')
      #twitter_share= render_twitter(url: project_by_slug_url(permalink: @project.permalink))
      .clearfix

.clearfix
#project_embed.hide data-path=embed_panel_project_path(@project)
  = image_tag "loading.gif", class: 'loader'
.text
  p
    = @project.about_html.html_safe

app/views/projects/_project_edit.html.slim
.bootstrap-twitter
  .alert.alert-info
    p
      = "Para saber tudo sobre como estruturar o seu projeto, baixe o #{link_to 'Guia Completo', "#{Configuration[:base_url]}/guia_realizadores.pdf", target: '_blank'}".html_safe
.bootstrap-form
  = semantic_form_for @project do |form|
    = form.inputs do
      - if current_user.admin
        = form.input :user_id
        = form.input :permalink, as: :string
      - if can? :update, @project, :name
        = form.input :name, as: :string, required: false
      - if can? :update, @project, :headline
        = form.input :headline, as: :string, required: false
      - if can? :update, @project, :category
        = form.input :category, as: :select, required: false
      - if can? :update, @project, :video_url
        = form.input :video_url, as: :string, hint: t('formtastic.hints.project.video_url_edit'),required: false
      - if can? :update, @project, :uploaded_image
        = form.input :uploaded_image, as: :file, required: false,
          hint: (@project.uploaded_image.present? ? image_tag(@project.uploaded_image.project_thumb.url, size: '220x172') : t('formtastic.hints.project.uploaded_image') )
      - if can? :update, @project, :online_days
        = form.input :online_days, as: :number, required: false
      - if can? :update, @project, :goal
        = form.input :goal, as: :number, required: false, hint: t('formtastic.hints.project.goal').html_safe
      - if can? :update, @project, :about
        = form.input :about, required: false
        = render 'formatting_tips'

      .clearfix
      .form-actions.bootstrap-twitter
        = form.submit class: 'btn'

app/views/projects/_project_reports.html.slim
- selected_r = @project.selected_rewards
ul
  li
    .bootstrap-twitter
      .alert.alert-info
        p
          = t('projects.show.reports.link_reports')
          = link_to t('projects.show.reports.all_backers'), reports_backer_reports_for_project_owners_path(project_id: @project.id, format: :csv)
  li
    .bootstrap-twitter
      .alert.alert-info
        p
          = t('projects.show.reports.link_reports')
          = link_to t('projects.show.reports.all_backers_without_reward'), reports_backer_reports_for_project_owners_path(project_id: @project.id, reward_id: 0, format: :csv)
  - if selected_r.length > 0
      - selected_r.each do |reward|
        li
          .bootstrap-twitter
            .alert.alert-info
              p
                = t('projects.show.reports.link_reward')
                = link_to reward.display_minimum, reports_backer_reports_for_project_owners_path(project_id: @project.id, reward_id: reward.id, format: :csv)

app/views/projects/_recommended_header.html.slim
#recommended_header
  .resume_about
    = image_tag "catarse/box_#{I18n.locale}.jpg"
    .bootstrap-form
      = form_tag(guidelines_path, method: :get, id: 'guidelines_form') do
        fieldset
          .bootstrap-twitter
            .button
              = link_to t('.guidelines'), guidelines_path, class:'btn_explore'
              span = t('.guidelines_subtitle')
  .project_info
    - if current_user
      - if @recommended_project
        = render partial: "project_header", locals: {title: t('projects.recommended_header.suggest_for_you'), project: @recommended_project}
      - else
        = render partial: "project_header", locals: {title: t('projects.recommended_header.highlight_project'), project: @fourth_project} if @fourth_project
    - else
      = render partial: "project_header", locals: {title: t('projects.recommended_header.highlight_project'), project: @fourth_project} if @fourth_project
  .clearfix

app/views/projects/_rejected_warning.html.slim
br
#project_warning.bootstrap-alert
  .alert.alert-warning
    i ATENÇÃO!  Este projeto foi rejeitado
    #toggle_warning
      = link_to '(minimizar informações)', '#'
    #project_warning_text
      br/
      br/
      | Esse projeto não se enquadra aos nossos <a href='https://docs.google.com/document/d/1Heh9LlvoSoD0lUfbmV5WlISJ3nqmGpEQiw15TBuCn-0/edit' target='_blank'>critérios de seleção.</a>

app/views/projects/_twitter_timeline.html.slim
javascript:
	!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/projects/embed_panel.html.slim
- box_width = "240px"
- box_height = "425px"
- video_width = "384px"
- video_height = "425px"
#project_box_embed
  iframe frameborder='0' height=box_height width=box_width src=embed_project_path(@project)
  form.html= text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '"></iframe>', readonly: true
#project_video_embed
  iframe frameborder='0' height=video_height width=video_width src=video_embed_project_path(@project)
  form.html= text_area_tag 'project_video_embed_html', '<iframe frameborder="0" height="' + video_height + '" src="' + video_embed_project_url(@project) + '" width="' + video_width + '"></iframe>', readonly: true
.clearfix

app/views/projects/index.html.slim
.banner
  p.post-author= t('main.banner')
#page_content
  .container
    .main
      - if current_user && @projects_near.present?
        section.near_projects.list
          header
            h2.list-title= t('sections.near.title')
            = link_to t('main.links.near'), explore_path(anchor: :near), class: "more-projects"
          .projects
            == render @projects_near

      section.selected_projects.list
        header
          h2.list-title= t('sections.selection.title')
          = link_to t('main.links.selected'), explore_path(anchor: :recommended), class: "more-projects"
        .projects
          == render @recommends

      section.channel_projects.list
        header
          h2.list-title= t('sections.channels.title')
          = link_to t('main.links.channels'), root_url(subdomain: 'asas'), class: "more-projects"
        .projects
          == render @channel_projects

      section.expiring_projects.list
        header
          h2.list-title= t('sections.expiring.title')
          = link_to t('main.links.expiring'), explore_path(anchor: :expiring), class: "more-projects"
        .projects
          == render @expiring

      section.recents_projects.list
        header
          h2.list-title= t('sections.recents.title')
          = link_to t('main.links.recents'), explore_path(anchor: :recent), class: "more-projects"
        .projects
          == render @recent

    aside.main-sidebar
      section.main-sidebar-division
        h3.title= t('sidebar.titles.blog')
        ul
          - (Blog.fetch_last_posts rescue [])[0..2].each do |post|
            li.post
              h2
                = link_to post.url, target: '__blank', class: 'post-title' do
                  /= image_tag("catarse/post_title_image.png")
                  = truncate(post.title, length: 80)
              p.post-author= "#{t('projects.box.by')} #{post.author} #{t('projects.box.when')} #{l(post.published.to_date)}"
              = link_to post.url, target: '__blank', class: 'post-resume' do
                = truncate(post.summary, length: 130).html_safe

      section.main-sidebar-division
        h3.title= t('sidebar.titles.newsletter')
        = form_tag Configuration['mailchimp_url'], id: 'mailee-form', method: 'post', class: 'newsletter' do
          = email_field_tag 'EMAIL', nil, placeholder: t('sidebar.placeholders.email'), label: 'email', class: 'newsletter-input'
          = submit_tag t('sidebar.buttons.newsletter'), class: 'newsletter-submit'


      section.main-sidebar-division
        .fb-like-box data-href="#{Configuration['facebook_url']}" data-width="200" data-height="300" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"


      section.main-sidebar-division
        = link_to t('sidebar.titles.twitter'), "https://twitter.com/#{Configuration['twitter_username']}", class: 'twitter-timeline', data:{widget_id:"375343843308089345", chrome:"nofooter"}

    .clearfix

app/views/projects/show.html.slim
= content_for :meta_tags do
  - if @update
    meta name="description" content=@update.title
    meta property="og:title" content=@update.title
    meta property="og:description" content=@update.comment
    meta property="og:url" content=project_by_slug_url(@project.permalink, update_id: @update.id, locale: I18n.locale)
  - else
    meta name="description" content=@project.headline
    meta property="og:title" content=@project.name
    meta property="og:description" content=@project.headline
    meta property="og:url" content=project_by_slug_url(@project.permalink, locale: I18n.locale)
  meta property="og:type" content='cause'
  meta property="og:image" content=@project.display_image('project_thumb_facebook')
  meta property="og:site_name" content=::Configuration[:company_name]
  meta property="fb:admins" content="#{fb_admins}"

#page_content
  .container

    - if @project.draft?
      = render "draft_warning"

    - if @project.rejected?
      = render "rejected_warning"

    - if @project.online? && can?(:update, @project)
      = render "online_warning"

    - if @project.waiting_funds? && can?(:update, @project)
      = render "waiting_funds_warning"

    - if @project.successful? && can?(:update, @project)
      = render "successful_warning"

    - if @project.failed? && can?(:update, @project)
      = render "failed_warning"

    #project_description
    .project_image
      = image_tag @project.display_image('project_thumb_small')
    .section_header
      h1= @project.name
      h4= t('projects.project_header.without_city', category_name: link_to(@project.category, explore_path(anchor: "by_category_id/#{@project.category_id}")), author: link_to(@project.user.display_name, user_path(@project.user))).html_safe
    .tab_container
      nav#project_menu
        = link_to '#about', 'id' => 'about_link', 'class' => 'selected', 'data-target' => '#project_about.content' do
          = t('.menu.about')
        = link_to '#updates', 'id' => 'updates_link', 'data-target' => '#project_updates' do
          = t('.menu.updates')
          span.count=" (#{@updates_count})"
        = link_to '#backers', 'id' => 'backers_link', 'data-target' => '#project_backers' do
          = t('.menu.backers')
          span.count=" (#{@project.total_backers})"
        = link_to '#comments', 'id' => 'comments_link', 'data-target' => '#project_comments' do
          = t('.menu.comments')
          | &nbsp; (
          fb:comments-count href="#{request.url}"
          | )
        - if can? :update, @project
          = link_to '#edit', 'id' => 'edit_link', 'data-target' => '#project_edit' do
            = t('.menu.edit')
          = link_to '#reports', 'id' => 'reports_link', 'data-target' => '#project_reports' do
            = t('.menu.reports')
    .main
      #project_content
        - if can? :update, @project
          #project_reports.content.hide
            = render partial: 'project_reports'
          #project_edit.content.hide
            = render partial: 'project_edit'

        #project_updates.content.hide[data-path=project_updates_path(project_id: @project.id)]
          - if can? :update, @project
            = render template: 'projects/updates/new'
          .results &nbsp;
          .clearfix
          #updates-loading.loading= image_tag "loading.gif"
        #project_backers.content.hide[data-path=project_backers_path(project_id: @project.id)]
          - if can?(:update, @project)
            = radio_button_tag(:backer_state, "available_to_count", checked: true)
            = label_tag(:backer_state, t('projects.project_backers.confirmed'))
            = radio_button_tag(:backer_state, "waiting_confirmation")
            = label_tag(:backer_state, t('projects.project_backers.pending'))
          .results &nbsp;
          .clearfix
          #backers-loading.loading= image_tag "loading.gif"
        #project_comments.content.hide
        #project_about.content= render 'project_about'

      .clearfix
    .sidebar
      .info
        #statistics
          .statistics
            .item.backers
              p= @project.total_backers
              em= t('statistics.backers.subtitle')
            .item.goal
              p= @project.display_pledged
              em= t('statistics.goal.subtitle', total: @project.display_goal).html_safe
            .item.time
              - if @project.draft? || @project.rejected?
                p= @project.online_days
                em #{@project.online_days} #{pluralize_without_number(@project.online_days, I18n.t('datetime.prompts.day').downcase)} #{pluralize_without_number(@project.online_days, t('remaining_singular'), t('remaining_plural'))}
              - else
                p= @project.remaining_days
                em #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}

          #condition[class="#{@project.display_status}"]
            p
              = t("projects.back_project.display_status.#{@project.display_status}", goal: @project.display_goal, date: @project.display_expires_at)
          - if @project.online? && @project.in_time?
            #pledge
              = form_tag(new_project_backer_path(@project), method: :get, id: 'back_project_form') do
                fieldset
                  = submit_tag t('projects.back_project.submit'), disabled: (not @project.online?)
        #creator_profile
          h3= t('project_by')
          .avatar = @project.user.display_image_html width: 80, height: 80
          .personal_info
            p.name
             = link_to @project.user.display_name, user_path(@project.user)
            #bio
              p= @project.user.bio
          #city
            p.backer= t('count_backed_projects', total: @project.user.total_backed_projects)
            p.city
              | #{@project.user.address_city}
        .user_social
          ul
            - if @project.user.facebook_link
              li
                = link_to "Perfil no facebook", @project.user.facebook_link, target: '_blank', class: 'facebook'
            - if @project.user.twitter
              li
                = link_to "Perfil no twitter", @project.user.twitter_link, target: '_blank', class: 'twitter'
            - if @project.user.email
              li
                = mail_to @project.user.email, @project.user.email, target: '_blank', class: 'email'
            - if @project.user.other_link
              li.other
                = link_to @project.user.other_link, @project.user.other_link, target: '_blank'

        .clearfix
        - if can?(:update, @project)
          .bootstrap-twitter.bootstrap-form
            .alert.alert-info
              h4.alert-header= t('.no_rewards_warning_title')
              p style="margin:0; padding:0;"
                = t('.no_rewards_warning')
              br/
              .new_reward_content.hide
                = image_tag 'loading.gif'

            .clearfix
            = link_to t('.menu.add_reward'), 'javascript:void(0);', data: {target: '.new_reward_content', path: new_project_reward_path(@project)}, class: 'btn btn-success pull-right show_reward_form'
            .clearfix

            br/
            /.skull-modal.new_reward_content.hide
              .skull-modal-header
                h3= t('projects.rewards.new_reward')
                a class='skull-modal-close' href='javascript:void(0);' &times;
              .skull-modal-body
                = image_tag 'loading.gif'
        #rewards[data-can_update="#{can?(:update, @project)}" data-index_path=project_rewards_path(@project)]
          .reward-loader= image_tag 'loading.gif'

    .clearfix